apiVersion: mutations.gatekeeper.sh/v1
kind: Assign
metadata:
  name: assign-scheduling
  namespace: default
spec:
    match:
      scope: Namespaced
      kinds:
        - apiGroups: ["greenops.greenops.test"]
          kinds: ["VirtualMachine"]
    applyTo:
    - groups: ["greenops.greenops.test"]
      kinds: ["VirtualMachine"]
      versions: ["v1"]
    location: "spec.scheduling[type:*].decision"
    parameters:
      assign:
        externalData:
          provider: external-data-provider
          dataSource: ValueAtLocation
          failurePolicy: Fail